---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deployment2
  labels:
    app: facebook
    env: lab
spec:
  selector:
    matchLabels:
      app: facebook
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: fb-pod
      labels:
        app: facebook
        env: lab
    spec:
      containers:
        - name: fb-pod2
          image: thajuddin9339/batch15:facebook_httpd
          ports:
            - containerPort: 8080
