---
apiVersion: v1
kind: Service
metadata:
  name: fb-loadbalancer-svc
  labels:
    app: facebook
    env: lab
spec:
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: facebook
